import SessionProviderContext from '@/contexts/SessionProviderContext';
import './globals.css';
import { Poppins } from 'next/font/google';
import RootLayoutWrapper from './(home)/RootLayoutWrapper';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
        />
      </head>
      <body className={poppins.className}>
        <SessionProviderContext>
          <RootLayoutWrapper>{children}</RootLayoutWrapper>
        </SessionProviderContext>
      </body>
    </html>
  );
}
