name: CI/CD + Docker + S3

on:
  push:
    branches:
      - main
      - munia_dev

jobs:
  munia-app-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check Docker version
        run: docker --version

      - name: Build Docker image
        run: docker build -t munia-app:latest .

      - name: Run Docker Container
        run: docker run -d -p 3002:3002 --name munia-app-test munia-app:latest

      - name: List run docker container
        run: docker ps

      - name: upload docker folder to s3
        run: aws s3 cp ./test-folder s3://munia-qa-bucket/ --recursive --region eu-north-1

      - name: Stop docker container
        if: always()
        run: |
          docker stop munia-app-test || true
          docker rm munia-app-test || true
